baseURL = "https://harrisonparadise.com/"
languageCode = "en-us"
title = "HP"
theme = "hugo-theme-cactus"

# Main menu is the top nav bar
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 4

[params]
  colortheme = "dark"

  # Home Page Settings
  description = "Hello World. I am Harrison Paradise. I currently lay bricks at Metropolis. I founded Sewn Commerce."

  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 4



[[params.social]]
  name = "spotify"
  link = "https://open.spotify.com/playlist/5WV2BMJCkJOaExbZ0Gt53s?si=whAhZtY9TreOqqWlkrBx7A"
[[params.social]]
  name = "email"
  link = "harrisonparadise@gmail.com" # no need for "mailto:" at the start
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/harrison-paradise-b1513b142/"
